### ISSUE TITLE
problem running example.py with Telephus 0.7

### ISSUE THREAD

**Issue by mateo41** [driftx/Telephus#6]
Hi folks,

I've tried using the release python-telephus_0.7~beta3.3.tar.gz from
http://debian.riptano.com/debian/pool/. I installed telephus into a new virtualenv and I used easy_install to install thrift. The thrift version is 0.2.0. I'm also running cassandra-0.7 on the host.

I run the example.py file and I get the following stack trace below. Does anybody have
an idea where this error is coming from? I think the error might be coming from the fastbinary.encode_binary call? Can anybody else reproduce this?

Thanks,
Matt Rodriguez

2010-12-03 15:40:23-0800 [-] Starting factory <telephus.protocol.ManagedCassandraClientFactory instance at 0x102900290>
2010-12-03 15:40:23-0800 [Uninitialized] Unhandled error in Deferred:
2010-12-03 15:40:23-0800 [Uninitialized] Unhandled Error
    Traceback (most recent call last):
      File "/Users/mateo/src/Telephus/telephus/protocol.py", line 219, in submitRequest
        return self.queue.get().addCallback(_process)
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/internet/defer.py", line 195, in addCallback
        callbackKeywords=kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/internet/defer.py", line 186, in addCallbacks
        self._runCallbacks()
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/internet/defer.py", line 328, in _runCallbacks
        self.result = callback(self.result, _args, *_kw)
    --- <exception caught here> ---
      File "/Users/mateo/src/Telephus/telephus/protocol.py", line 210, in _process
        d = proto.submitRequest(request)
      File "/Users/mateo/src/Telephus/telephus/protocol.py", line 92, in submitRequest
        d = fun(*request.args)
      File "/Users/mateo/src/Telephus/telephus/cassandra/Cassandra.py", line 730, in insert
        self.send_insert(key, column_parent, column, consistency_level)
      File "/Users/mateo/src/Telephus/telephus/cassandra/Cassandra.py", line 741, in send_insert
        args.write(oprot)
      File "/Users/mateo/src/Telephus/telephus/cassandra/Cassandra.py", line 4044, in write
        oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
    exceptions.TypeError: an integer is required

**Comment by thepaul** [comment]
Hey- this looks offhand like a mismatch in the thrift protocol version. There is no official Cassandra 0.7 release yet, but there have been some betas and a release candidate. Can you confirm which sort of Cassandra 0.7 you're working with?

**Comment by driftx** [comment]
Actually, example.py was out of date.  Fixed in unstable.

**Comment by mateo41** [comment]
Thanks for you help on this. The problem in my code was I passing in a keyspace argument when I instantiated the CassandraClient. The 0.7 branch Cassandra client does not have a keyspace as one of its arguments, whereas the 0.6 branch does. 

If you do pass in the keyspace argument you get the above stack trace whenever the protocol tries to write something. 

Thanks,
Matt
